### ISSUE TITLE
Question regarding ComponentListener

### ISSUE THREAD

**Issue by marko995** [Quillraven/MysticWoods#7]
Hi, is there any alternative to ComponentListener in new fleks 2.6?
I don't want to provide GameStage in the component, so my idea is to create a system where it adds Image to actor, is that ok or there is a better solution?

https://github.com/Quillraven/MysticWoods/blob/fd44fa58a07f450046be6ea58f64b0e6d62313f9/core/src/main/kotlin/com/github/quillraven/mysticwoods/component/ImageComponent.kt#L28

**Comment by Quillraven** [comment]
@marko995 :

There are multiple way to solve such initialization problems.

One way is like you describe it which means you do it in a system. Imo this is totally fine and that is the approach that I used for a long time with Ashley ECS.

The downside to this approach is when your game becomes more complex and has lots of systems. If some systems require the image information and they run before your system that initializes the image then you need to add special conditions in those systems to take care of this scenario. 



The second approach are component listeners (or hooks in Fleks 2.x) which are imo more elegant and bypass the downside of the first approach.



The third approach that I prefer nowadays is to set such initial values directly in the component constructor. Since Fleks 2.x does not use reflection anymore, the component creation is just a typical object instance creation where you can already pass the required arguments.
I then have an extension function for the world that creates a character or prop or whatever entity. In this function I can already get the image of the entity immediately and pass it to the component constructor. 
If the image logic has some caching or special logic parts to it then I still add this logic to a system that makes sense. In the extension function to create a specific entity I can then just get the system with world.system() and call its methods to get the image for the component constructor.

I prefer this way over the others because it does not require a listener/hook, has no delay to init the value AND has the upside that I could make the image of the component a val instead of var (immutable) and also set no default value for this component field to make it clear that it is required from the beginning and must be set by a user.



There are most likely other approaches as well but those are the ones that I used in the past .

Hope that helps!

**Comment by marko995** [comment]
Thanks for the fast response :D
If you have time, can you give me a rough example of hook approach?

I closed this because I found your fleks-2.0 branch. I checked how you did there, and looks nice, is that the third approach?

**Comment by Quillraven** [comment]
That is still the second approach which is good enough imo.

The third approach would be something like this:

```kotlin
data class ImageComponent(val image:  FlipImage, var layer: Int = 0) : Component<ImageComponent> {
    override fun type() = ImageComponent

    companion object : ComponentType<ImageComponent>()
}

fun World.character() : Entity = world.entity {
  val stage = inject<Stage>()
  val image = // ... logic to retrieve flipimage for entity
  stage.addActor(image)

  it += ImageComponent(image) // pass it directly as component constructor argument
}
```

Most likely I'd still add a onRemove hook to remove the actor from the stage. With this approach you can have a data class which has some benefits when it comes to debugging and imo it is nicer that you directly see from the component's constructor what kind of arguments are required and which ones are optional.

**Comment by marko995** [comment]
thanks! the second approach would be enough for my game :D
